# config/flight-tracker-service.yml

server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/flightplatform
  datasource:
    url: jdbc:postgresql://localhost:5433/flightplatform
    username: flightuser
    password: flightpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5433/flightplatform
    user: flightuser
    password: flightpass

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: flight-tracker-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.flightplatform.common.event"
        spring.json.value.default.type: com.flightplatform.common.event.FlightPositionEvent